# Logging configuration for Bajabongo Engine
#
# Sets the minimum level of logs to be shown for each category.
# Levels: trace, debug, info, warn, error, critical, off
#The hierarchy of importance is:
#trace -> debug -> info -> warn -> error -> critical
#(Least important -> Most important)

[loggers]
Game = debug
Input = debug
Core = info
Physics = debug
Renderer = warn
GameplayState = debug