# Logging configuration for Bajabongo Engine
#
# Sets the minimum level of logs to be shown for each category.
# Levels: trace, debug, info, warn, error, critical, off

[loggers]
Core = info
Physics = debug
Renderer = warn