#pragma once

#include <entt/entity/entity.hpp>

namespace engine
{
    /**
     * @brief Fired when two solid physics shapes begin touching.
     * * Use this for impact logic (e.g., bullet hits wall, player hits ground).
     * * This event is generated by the ContactListener in the PhysicsSystem.
     */
    struct PhysicsContactBeginEvent
    {
        entt::entity entityA;
        entt::entity entityB;
    };

    /**
     * @brief Fired when two solid physics shapes stop touching.
     * * Use this for logic like "player left the ground" (coyote time).
     */
    struct PhysicsContactEndEvent
    {
        entt::entity entityA;
        entt::entity entityB;
    };

    /**
     * @brief Fired when a shape enters a sensor (trigger) volume.
     * * Sensors detect overlap but do not cause physical collision response.
     * * Use this for zones (e.g., extraction point, damage area, item pickup).
     */
    struct PhysicsSensorBeginEvent
    {
        entt::entity sensorEntity;  ///< The entity that owns the sensor fixture.
        entt::entity visitorEntity; ///< The entity that entered the sensor area.
        
        /**
         * @brief True if the visitor's fixture is ALSO a sensor.
         * * Often used to filter out Sensor-vs-Sensor interactions (e.g., a radar area shouldn't pick up a loot trigger).
         */
        bool isVisitorSensor;       
    };

    /**
     * @brief Fired when a shape exits a sensor (trigger) volume.
     */
    struct PhysicsSensorEndEvent
    {
        entt::entity sensorEntity;
        entt::entity visitorEntity;
    };
}